name: Run test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [pypy3.10, "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup Python with uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          prune-cache: false # do not remove pre-built wheels
          ignore-nothing-to-cache: true
          cache-dependency-glob: "**/requirements.txt"

      - name: hint on cache hit
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Hit cache"

      - name: install dependencies
        run: uv pip install -r requirements.txt

      - name: execute py script
        run: python -m swc -i=${{ secrets.STEAMUID }} -d=True
